"""
ComfyUI节点初始化文件
"""
from .lifegame_node import NODE_CLASS_MAPPINGS as LIFEGAME_NODE_CLASS_MAPPINGS
from .lifegame_node import NODE_DISPLAY_NAME_MAPPINGS as LIFEGAME_NODE_DISPLAY_NAME_MAPPINGS

# 合并节点映射
NODE_CLASS_MAPPINGS = {
    **LIFEGAME_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LIFEGAME_NODE_DISPLAY_NAME_MAPPINGS,
}
